# Python stubs generated by omniidl from test.idl

import omniORB, _omnipy
from omniORB import CORBA, PortableServer
_0_CORBA = CORBA

_omnipy.checkVersion(3,0, __file__)


#
# Start of module "MyData"
#
__name__ = "MyData"
_0_MyData = omniORB.openModule("MyData", r"test.idl")
_0_MyData__POA = omniORB.openModule("MyData__POA", r"test.idl")


# struct Blag
_0_MyData.Blag = omniORB.newEmptyClass()
class Blag (omniORB.StructBase):
    _NP_RepositoryId = "IDL:MyData/Blag:1.0"

    def __init__(self, val1, val2):
        self.val1 = val1
        self.val2 = val2

_0_MyData.Blag = Blag
_0_MyData._d_Blag  = (omniORB.tcInternal.tv_struct, Blag, Blag._NP_RepositoryId, "Blag", "val1", omniORB.tcInternal.tv_ulong, "val2", omniORB.tcInternal.tv_ulong)
_0_MyData._tc_Blag = omniORB.tcInternal.createTypeCode(_0_MyData._d_Blag)
omniORB.registerType(Blag._NP_RepositoryId, _0_MyData._d_Blag, _0_MyData._tc_Blag)
del Blag

#
# End of module "MyData"
#
__name__ = "test_idl"

_exported_modules = ( "MyData", )

# The end.
