#!/usr/bin/env python
# -*- Python -*-
# -*- coding: utf-8 -*-

'''rtshell

Copyright (C) 2009-2014
    Geoffrey Biggs
    RT-Synthesis Research Group
    Intelligent Systems Research Institute,
    National Institute of Advanced Industrial Science and Technology (AIST),
    Japan
    All rights reserved.
Licensed under the Eclipse Public License -v 1.0 (EPL)
http://www.opensource.org/licenses/eclipse-1.0.txt

Command to manage component configuration.

'''


import sys

from rtshell import rtconf


if __name__ == '__main__':
    res, lines = rtconf.main()
    for l in lines:
        print l
    sys.exit(res)

# vim: tw=79

