#!/usr/bin/env python
# -*- Python -*-
# -*- coding: utf-8 -*-

'''rtcshell

Copyright (C) 2009-2010
    Geoffrey Biggs
    RT-Synthesis Research Group
    Intelligent Systems Research Institute,
    National Institute of Advanced Industrial Science and Technology (AIST),
    Japan
    All rights reserved.
Licensed under the Eclipse Public License -v 1.0 (EPL)
http://www.opensource.org/licenses/eclipse-1.0.txt

File: rtdel

Delete an object from a name server.

'''

__version__ = '$Revision: $'
# $Source$


import sys

from rtcshell import rtdel


if __name__ == '__main__':
    sys.exit(rtdel.main())


# vim: tw=79

