#!/usr/bin/env python2
# -*- Python -*-
# -*- coding: utf-8 -*-

'''rtshell

Copyright (C) 2009-2015
    Geoffrey Biggs
    RT-Synthesis Research Group
    Intelligent Systems Research Institute,
    National Institute of Advanced Industrial Science and Technology (AIST),
    Japan
    All rights reserved.
Licensed under the GNU Lesser General Public License version 3.
http://www.gnu.org/licenses/lgpl-3.0.en.html

Command to find components, managers, etc.

'''


import sys

from rtshell import rtfind


if __name__ == '__main__':
    res, matches = rtfind.main()
    for m in matches:
        print(m)
    sys.exit(res)


# vim: tw=79

