# DO NOT EDIT THIS FILE!
#
# Python module MyData generated by omniidl

import omniORB
omniORB.updateModule("MyData")

# ** 1. Stub files contributing to this module
import test_idl

# ** 2. Sub-modules

# ** 3. End
